version: '3'
services:
  robot:
    build:
      context: '.'
      dockerfile: './dockerfile'
      shm_size: '2gb'
    volumes:
      - ./:/robot
    ulimits:
      core:
        hard: 0
        soft: 0  