version: '3.5'
services:
  robot:
    build:
      context: '.'
      dockerfile: './dockerfile_pi'
      shm_size: '4gb'      
    volumes:
      - ./:/robot
    deploy:
      	resources:
      		limits:
      			memory: 4G
      		reservations:
      			memory: 2G	  
    ulimits:
      core:
        hard: 0
        soft: 0  