version: '3.5'
services:
  robot:
    build:
      context: '.'
      dockerfile: './dockerfile_pi'
      shm_size: '4gb'
    volumes:
      - ./:/robot
    ulimits:
      core:
        hard: 0
        soft: 0  